### ISSUE TITLE
Dúvida: Descontos

### ISSUE THREAD

**Issue by marlaaragao** [BoletoSimples/boletosimples-php#5]
Boa tarde, tenho uma dúvida: como lidar com descontos do boleto? No arquivo remessa, por exemplo, nos segmentos Q e R os campos Desconto 2 e Desconto 3 estão presentes. Esses descontos são informados como ao criar o boleto?

**Comment by kivanio** [comment]
Olá,

hoje não usamos esses campos na API.
Se for uma necessidade, pedimos para a equipe avaliar a inclusão deles.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2017-02-03 8:30 GMT-03:00 marlaaragao <notifications@github.com>:

**Comment by marlaaragao** [comment]
Ah sim, entendi, mas no caso pode ser informado ao menos um desconto? Obrigada!

**Comment by kivanio** [comment]
Hoje não.

Você pode informar na ‘instrução ao caixa' do boleto.

Até porque o valor pago não é validado pelo banco ainda.
O cliente pode pagar o valor que quiser.

E se for na boca do caixa, o caixa lê as instruções e aplica o desconto.


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by marlaaragao** [comment]
Entendi! Muito obrigada, era só essa dúvida mesmo!
