### ISSUE TITLE
Duplicar Boleto

### ISSUE THREAD

**Issue by matheusdelima** [BoletoSimples/boletosimples-php#7]
Pessoal, tenho o seguinte problema, quando utilizo a função **duplicate** como segue o código abaixo. Todavia a seguinte mensagem de erro aparece:
**Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON**
```

$data = [
            'id' => $this->getParam('bsID'),
            'expire_at_in_days' => date('d/m/Y', strtotime("+7 days",strtotime(date("d-m-Y")))),
            'amount' => number_format(405, 2, ',', '')
 ];
try {
            $boleto = new BoletoSimples\BankBillet();   
            $boleto->duplicate(array('id' => 329603));
}catch (Exception $e){
           echo $e->getMessage();
}

```

Alguém já passou por isto?

**Comment by kivanio** [comment]
Algo está fora de formato.
Veja se consegue printar o json para poder ver o que é.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by matheusdelima** [comment]
Infelizmente não me retorna nenhum JSON, segue abaixo as respostas do tratamento do framework para ver se auxilia :(

## **Stack trace: **

`#0 /home/sbn/public_html/zend_framework/library/MinhasClasses/boletosimples/boletosimples/src/BoletoSimples/ResponseError.php(17): GuzzleHttp\Message\Response->json()
#1 /home/sbn/public_html/zend_framework/library/MinhasClasses/boletosimples/boletosimples/src/BoletoSimples/Resources/BaseResource.php(152): BoletoSimples\ResponseError->__construct(Object(GuzzleHttp\Message\Response))
#2 [internal function]: BoletoSimples\BaseResource::_sendRequest('POST', 'bank_billets/du...', Array)
#3 /home/sbn/public_html/zend_framework/library/MinhasClasses/boletosimples/boletosimples/src/BoletoSimples/Resources/BaseResource.php(167): call_user_func_array('self::_sendRequ...', Array)
#4 /home/sbn/public_html/zend_framework/library/MinhasClasses/boletosimples/boletosimples/src/BoletoSimples/Resources/BankBillet.php(12): BoletoSimples\BaseResource::__callStatic('sendRequest', Array)
#5 /home/sbn/public_html/zend_framework/library/MinhasClasses/boletosimples/boletosimples/src/BoletoSimples/Resources/BankBillet.php(12): BoletoSimples\BankBillet::sendRequest('POST', 'bank_billets/du...', Array)
#6 /home/sbn/public_html/zend_framework/application/controllers/FinanceiroController.php(1073): BoletoSimples\BankBillet->duplicate(Array)
#7 /home/sbn/public_html/zend_framework/library/Zend/Controller/Action.php(516): FinanceiroController->boletosSegundaViaAction()
#8 /home/sbn/public_html/zend_framework/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('boletosSegundaV...')
#9 /home/sbn/public_html/zend_framework/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /home/sbn/public_html/zend_framework/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /home/sbn/public_html/zend_framework/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /home/sbn/public_html/zend_framework/public_html/index.php(30): Zend_Application->run()
#13 {main}  `

**Comment by matheusdelima** [comment]
?

**Comment by DaniloTerra** [comment]
@matheusdelima analisei o código da lib e a documentação desse endpoint na API. Acredito que ajustando o código para esse formato dê certo. Poderia verificar, por favor?

```
$boleto = new BoletoSimples\BankBillet(['id' => 329603]);
$boleto->duplicate([]);
```

**Comment by luxu** [comment]
@matheusdelima Desenvolveu em ZF 1,2 ou 3?

**Comment by matheusdelima** [comment]
zf 1



2017-12-27 8:18 GMT-03:00 Luciano da Silva Martins <notifications@github.com

**Comment by kivanio** [comment]
Pessoal, tentamos manter exemplos de uso em:
https://github.com/BoletoSimples/boletosimples-php-test

https://github.com/BoletoSimples/boletosimples-php-test/blob/master/index.php#L134
